version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=find-friend-api
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
